name: notes_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  google_generative_ai: any
  
  # State Management
  provider: ^6.1.1
  
  # Database (Mobile)
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.8.3

  # Database (Web support)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utils
  uuid: ^4.3.3
  flutter_dotenv: ^5.1.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Hive model generator (optional but safe to include)
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - .env
